apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod 
  template:
    metadata:
      labels:
        podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-container
        env:
        - name: CONFIGURATION_UI_LANGUAGE
          value: {{ tpl .Values.language . | quote | default "en" }}
        - name: CONFIGURATION_MODEL_SERVICE_URL
          value: {{ tpl .Values.modelServiceUrl . | quote }}
        - name: CONFIGURATION_MODEL_SERVICE_NAME
          value: {{ tpl .Values.modelServiceName . | quote }}
        - name: CONFIGURATION_JOB_SERVICE_URL
          value: {{ tpl .Values.jobServiceUrl . | quote }}
        - name: CONFIGURATION_JOB_SERVICE_NAME
          value: {{ tpl .Values.jobServiceName . | quote }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.port }}
