
# The port on which the service should listen
port: 8080

# Name of the image tu pull from registry
image: acrarolibotnonprod.azurecr.io/3d-model-ingestion-client:latest

language: en
modelServiceUrl: http://ingestion-stack-integ-3d-model-ingestion-service-route-3d-test.apps.v0h0bdx6.eastus.aroapp.io/
modelServiceName: /models
jobServiceUrl: http://ingestion-stack-integ-discrete-ingestion-db-route-3d-test.apps.v0h0bdx6.eastus.aroapp.io/
jobServiceName: /jobs

ingress:
  enabled: false

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

  path: "/"

  host: "minikube.local"

route:
  enabled: true

  # annotations:
  #   haproxy.router.openshift.io/rewrite-target: "/"