
# # The port on which the service should listen
# port: 8080

# Name of the image tu pull from registry
image: mapcolonies/3d-model-ingestion-client:latest

replicaCount: 1

language: en
modelServiceUrl: http://3d-model-ingestion-service/
modelServiceName: /models
jobServiceUrl: http://discrete-ingestion-db/
jobServiceName: /jobs

service:
  internalPort: 8080
  externalPort: 8080

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ printf \"%s-%s\" .Release.Name .Chart.Name | trunc 63 | trimSuffix \"-\" }} rewrite=/"

  path: "/"

  hosts: ["minikube.local"]

route:
  enabled: false

  # annotations:
  #   haproxy.router.openshift.io/rewrite-target: "/"